# Zeabur 部署配置
# 文档: https://zeabur.com/docs/deploy/dockerfile

services:
  # Grok2API 主服务
  - name: grok2api
    docker:
      # 使用根目录的 Dockerfile
      path: .
    ports:
      - 80:8000
    env:
      - STORAGE_MODE=file
      - WORKERS=1
      - PORT=8000
    volumes:
      - data:/app/data
      - keys:/app/keys
      - logs:/app/logs
